### ISSUE TITLE
future questions

### ISSUE THREAD

**Issue by mleklund** [theforeman/foreman_omaha#54]
Curious about where this is going.  Is this mostly targeted toward flatcar?  Will it ever support what has become Fedora/RH CoreOS?

**Comment by timogoebel** [comment]
@mleklund: Yes. Unfortunately the new CoreOS reinvented the wheel and does everything a little different. So the plugin is pretty much useless as the new CoreOS does not use the Omaha protocol anymore. So currently, this is supposed to work with Flatcar Linux. We have added patches to Foreman core to support Flatcar and are using both Flatcar and this plugin in core.

**Comment by mleklund** [comment]
That is what I figured and is fine.
